Assignments/sudoku (I haven't actually done sudoku yet, just wanted to show the program I made)
bhs-intro-to-programming/ionisea pull request #14
Opened 2022-11-30 23:33 UTC by ionisea

2022-12-01 16:37 UTC, gigamonkey requested changes
This is an interesting program. Left some comments about how you can make it clearer. Happy to explain logarithms to you if you haven't learned about them in math yet.

2022-12-01 16:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +  if (acc.length < 4 + i) return acc.substring(0, acc.length - i) + '.' + acc[acc.length - i] + (i/3 == 1 ? 'k' : i/3 == 2 ? 'm' : i/3 == 3 ? 'b' : i/3 == 4 ? 't' : '😵')
It's generally a good rule of thumb to try to keep lines under 80 characters. This line is more than twice that. And rather than just breaking this one big expression over multiple lines, break it up into  separate expressions that make it more clear what is going on. Maybe something like:

```javascript
  if (acc.length < 4 + i) {
    const unit = (i/3 == 1 ? 'k' : i/3 == 2 ? 'm' : i/3 == 3 ? 'b' : i/3 == 4 ? 't' : '😵');
    return acc.substring(0, acc.length - i) + '.' + acc[acc.length - i] + unit;
}
```

That `const unit` line is still a bit over 80 characters and also nested `?:` operators are also not usually the clearest thing. So I might switch that around to something like:

```javascript
  if (acc.length < 4 + i) {
    const unit = i/3 <= 4 ? 'kmbt'[i/3 - 1] : '😵';
    return acc.substring(0, acc.length - i) + '.' + acc[acc.length - i] + unit;
  }
```

Finally, shouldn't the `b` be a `g`?

2022-12-01 16:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +  console.log('current avg:', averageResults(logs.array))
Not only are these two lines quite long and using nested `?:` but also basically duplicating each other. So another place where it would be a good idea to break out a separate function, maybe something like:

```javascript
const renderNumber = (n, mode) => { ...
```

2022-12-03 16:58 UTC, ionisea commented
I've made some changes to the truncation function to where I don't need a loop anymore

2022-12-03 23:47 UTC, ionisea commented
I've made some further changes

2022-12-11 04:52 UTC, gigamonkey requested changes
Are you still working on this? I'm happy to approve it if you're done. If you do want to work on it more, maybe leave a comment on this PR about what aspects of the code you'd like me to focus on. I can give you general advice about simplifying and program structure. Or if there are particular problems you're trying to solve we can discuss those.

So, in short, please leave a comment about what you want to do with this so I know what to do next.

2023-01-07 17:03 UTC, gigamonkey commented
@ionisea Please decide what you're doing with this PR. Merge it if you're done working on it for now or leave a comment about what you'd like me to review. I'm getting tired of looking at it in the list of open PRs.

2023-01-07 17:06 UTC, merged