Assignments/tic tac toe
bhs-intro-to-programming/ionisea pull request #15
Opened 2022-12-02 19:05 UTC by ionisea

I think this may have fixed it

2022-12-02 21:09 UTC, gigamonkey approved these changes
This is looking pretty good. I left a bunch of comments on style and code structure. I may use this code as the basis for another video so you'll get to see all the details of how I'd structure this code if it was entirely up to me.

2022-12-02 21:14 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +  return drawLine(width/2 - height/2,height/6+height*(winner.winLoc/3), width/2 + height/2, height/6+height*(winner.winLoc/3), 'grey', 8)
I had the return left there from testing and forgot to remove it- thanks

2022-12-02 21:16 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +    player == player1 ? player = player2 : player = player1;
fixed

2022-12-02 21:19 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +let yPos;
moved

2022-12-02 21:26 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +let winner ={}
It seems to be used somewhere else in the code, as when I move it into the function it no longer works (I can place after the game ends). This is probably because of the redefinition of it within the function to where I add the win attributes to it, but maybe there is an occurrence I don't see.

2022-12-02 21:29 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +for (let editVar = 1/3; editVar < 1; editVar += 1/3){
Fixed.

2022-12-02 21:44 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +}
converted to a function and added being able to add borders

2022-12-02 21:50 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +    coordArray[yPos][xPos].push(player)
fixed this

2022-12-03 18:04 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +let winner ={}
Figured out the problem after looking at it again- because the player switches, the next turn it checks if the next player is the winner and sees no winner as it is again only checking the current player. My code currently works as it is keeping things assigned to the object, so when it is accessed again, it doesn't see a new win but the existing win in the object is still returned from the function. If that makes any sense.

2022-12-03 18:05 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +let winner ={}
Should I leave it as-is or check both players upon each wincheck?

2022-12-05 21:49 UTC, gigamonkey commented
@ionisea I went ahead and made a video to demonstrate some changes I'd make to this code. It came out kinda long so I understand if you don't want to watch the whole thing but there's definitely some good stuff in there that explains in more detail than I can in comments here how I think about code like this. You can see it here: https://www.youtube.com/watch?v=MW5fFLP2nc0

2022-12-06 04:31 UTC, gigamonkey requested changes
I see you trying a bunch of ways to represent the empty cells in the board. You're complicating it by adding a gratuitous layer of arrays. I talk about that near the end of the video I made for you so you might want to watch that. Or I can explain it in class tomorrow.

2022-12-06 04:31 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  [[''], [''], ['']],
This is still not quite right. These rows should be arrays of strings: `['', '', '']` not arrays of arrays of strings, which is what you have here.

2022-12-06 04:31 UTC, gigamonkey commented on assignments/tic-tac-toe/code.js
> +  if (coordArray[yPos][xPos] == '' && winSearch(player) == undefined){
Given the way you change `coordArray` this is still relying on the `==` to work.

2022-12-07 22:40 UTC, ionisea commented on assignments/tic-tac-toe/code.js
> +  [[''], [''], ['']],
fixed

2022-12-13 22:35 UTC, merged