turned into functions and added code- this wouldve been so much easier
bhs-intro-to-programming/ionisea pull request #26
Opened 2023-01-25 04:04 UTC by ionisea

only took a few minutes

2023-01-25 04:07 UTC, ionisea commented
i just realized the code isn't working, let me fix

2023-01-25 04:46 UTC, ionisea commented
it still doesn't work but now it is closer

2023-01-25 15:27 UTC, gigamonkey requested changes
This is very much the right idea. You just need to debug some pretty simple mistakes. Did you look in the Javascript console for errors because that should have pointed you pretty directly at the first problem.

2023-01-25 15:27 UTC, gigamonkey commented on projects/2023-01-17/public/scripts/script.js
> +const makePgrph = (text) => { // string
You may find that in general abbreviations are not worth it. Because the savings in typing (especially in a world where your editor can tab complete names for you) is less than the mental cost of remembering *how* you abbreviated something. So just go ahead and call this `makeeParagraph`.

2023-01-26 01:36 UTC, gigamonkey approved these changes
Really outstanding work! I think the only thing you missed was adding the `alt` attribute on the image and hardly anyone got that since it doesn't directly affect how the page looks in the browser.

2023-01-26 02:20 UTC, merged