Assignments/boolean birds
bhs-intro-to-programming/ionisea pull request #3
Opened 2022-09-09 00:35 UTC by ionisea

Completed assignment

2022-09-09 03:34 UTC, gigamonkey requested changes
Looks pretty good. Do please make the changes I suggested, partly to get practice at the flow. When you make changes, they will get added to this PR and then I'll be able to re-review and approve and then you can merge to `main`.

2022-09-09 03:34 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +function isRed (bird){
I looked at the history of your attempts to write this function. That was quite a journey. Congrats on sticking it out to the end. You are not the only one who had trouble with this one; I'll obviously have to go over what it means when I say a function "takes a single string" because that was the key here, as it looks like you eventually figured out.

2022-09-09 03:34 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +function isFlobbyBird(red,spotted){
As I commented on your first PR, while this syntax is legal Javascript it's not the one I'm using in this class, for few different reasons, some stylistic and some pedagogical. Anyway, as an exercise can you please translate these functions into the style I describe in the Functions slides.
```suggestion
const isFlobbyBird = (red,spotted) => {
  return red && spotted;
};
```

Or if—like me—you like concise code:


```suggestion
const isFlobbyBird = (red,spotted) => red && spotted;
```

2022-09-09 03:34 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +//function isRed (b1,b2,b3,b4){
Always a good idea to tidy up things like this and delete them. Especially since everything is in version control anyway, you can always get back to it if you really do.

2022-09-09 21:45 UTC, ionisea commented on assignments/boolean-birds/code.js
> +function isFlobbyBird(red,spotted){
Ok, switched to the Const syntax and removed the junk. Gave up on the concise bit cause it took too long lol.

2022-09-10 00:22 UTC, gigamonkey approved these changes
Looks good. Merge it!

2022-09-10 00:24 UTC, merged