incomplete
bhs-intro-to-programming/ionisea pull request #39
Opened 2023-04-10 22:31 UTC by ionisea

2023-04-11 22:26 UTC, ionisea commented
all but change are now done

2023-04-12 02:19 UTC, gigamonkey requested changes
Nice work! One more to go.

2023-04-12 02:19 UTC, gigamonkey commented on assignments/recursion/code.js
> +  } else {
This is fine but can you see an elegant way to combine these two base cases?

2023-04-12 02:19 UTC, gigamonkey commented on assignments/recursion/code.js
> +const sum = (ns) => { // You left this in the slides!
Well, you're the only one to have said anything about it. I wonder if you're the only one to have noticed.

2023-04-12 02:19 UTC, gigamonkey commented on assignments/recursion/code.js
> +  if (arr.at(-1) === val) {
I guess this works. `at` is a bit obscure so searching from the front with `arr[0] === val` might be more idiomatic. But this is fine.

2023-04-12 02:19 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return false
Styles vary on this but I kind of like to put the base case first and make it explicit so it's easy to see what it is rather than it being the default when nothing else works:

```javascript
if (arr.length === 0) {
  return false;
} else {
  // recursive case here with whatever logic is required
}
```

2023-04-12 22:02 UTC, ionisea commented on assignments/recursion/code.js
> +  if (arr.at(-1) === val) {
fixed

2023-04-15 23:59 UTC, gigamonkey approved these changes
Nice work. And good job wrestling with the `change` problem before I gave you all the big hint.

2023-04-17 21:53 UTC, ionisea commented
fixed the reverse string

2023-04-18 02:26 UTC, gigamonkey approved these changes

2023-04-18 21:51 UTC, merged