Assignments/pig latin
bhs-intro-to-programming/ionisea pull request #4
Opened 2022-09-12 21:59 UTC by ionisea

complete

2022-09-12 22:17 UTC, ionisea commented
Slightly optimized it

2022-09-13 00:40 UTC, gigamonkey requested changes
Good work. But please make the changes (variable names, no var, use one-arg version of `substring`) and then I'll approve it.

2022-09-13 00:40 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  const latin = string.search(/[aeiou]/)
You should work on using meaningful names. While `latin` is relevant to the topic it's not a meaningful name for this value. Since this value is the index of the first vowel I'd probably just call it `i` (which is pretty universally used to name index values). Or maybe `v`. Or even `firstVowel` if you want to be more verbose. But I'd use `i`.

2022-09-13 00:40 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  return string.substring(latin,string.length)+string.substring(0,latin)+'ay'
Remember that `substring` can be called with just one argument to extract from the given index to end end of the string. I.e. the second value defaults to the length of the string if not provided. So combining that fact with my rename of `latin` to `i`, (plus adding some spacing for readability) I'd write this line like:

```suggestion
  return string.substring(i) + string.substring(0, i) + 'ay';
```

2022-09-13 00:40 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const advancedPigLatin =(string)=>{
Same comments as the other function.

2022-09-13 00:40 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +var weiu = 3
What are these here for? They don't hurt anything but it's good to clean up your code before you post your PR and delete stuff like this that isn't needed.

2022-09-13 00:40 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  var advlatin = string.search(/[aeiou]/)
Why did you use `var` here. You should not use it; it's old fashioned and slightly broken. `const` is great for this since the variable never changes. And if you need to declare a variable that will change, use `let`.

2022-09-13 05:19 UTC, gigamonkey approved these changes
Looks good. Go ahead and merge.

2022-09-13 05:19 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +  return vLoc === 0? string.substring(0)+'way':string.substring(vLoc)+string.substring(0, vLoc)+'ay'
I may have missed this before but in the `vLoc === 0` case you don't need the `substring` at all. Just `string + 'way'` will do. But this also works.

2022-09-13 21:37 UTC, ionisea commented on assignments/pig-latin/code.js
> +  return vLoc === 0? string.substring(0)+'way':string.substring(vLoc)+string.substring(0, vLoc)+'ay'
That makes since, looking at it. Will keep that in mind in the future.

2022-09-13 21:37 UTC, merged