Assignments/recursion 2
bhs-intro-to-programming/ionisea pull request #40
Opened 2023-04-17 22:33 UTC by ionisea

recursion 2 electric boogaloo

2023-04-18 03:07 UTC, gigamonkey requested changes
Nice work. A few small points. And you can keep going to finish the rest.

2023-04-18 03:07 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return a
Don't really need this case; just let the recursive case handle it. But make sure you understand why that works.

2023-04-18 03:07 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return n;
Again, this case would be handled by the recursive case.

2023-04-18 03:07 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return deleteXs(str.substring(0, ind) + str.substring(ind + 1, str.length))
Okay, that's technically recursive so no real complaints. However, for grins, can you write this without using `indexOf`; the only character of the string you should ever look at is the first one (in any given call).

2023-04-18 21:58 UTC, ionisea commented
complete, looking forward to your complaints (especially about countXs)!

2023-04-19 00:03 UTC, gigamonkey approved these changes
Good job. My friend wants to know if you've ever actually seen _Breakin' 2: Electric Boogaloo_ and if so, what your review is.

2023-04-19 00:03 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +  }
This is fine and works. You can also show the relation between `every` and `&&` by rewriting this with an `&&`:

```javascript
return p(arr[0]) && every(arr.slice(1), p);
```

It's just as efficient since `&&` short-circuits and will prevent the recursive call if `p(arr[0])` is false.

2023-04-19 00:03 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +  }
Likewise, `some` and `||` have a close relationship:

```javascript
return p(arr[0]) || some(arr.slice(1), p);
```

Will also short-circuit so it returns true as soon as `p(arr[0])` does.

2023-04-19 19:41 UTC, ionisea commented on assignments/recursion-2/code.js
> +    return str;
fixed i believe

2023-04-19 22:12 UTC, ionisea commented
some things have been fixed

2023-04-20 01:10 UTC, gigamonkey approved these changes
Looks good. A couple comments about efficiency.

2023-04-20 01:10 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return every(arr.slice(1), p) && p(arr[0])
Note that it's actually potentially dramatically more efficient to write this as:

```javascript
    return p(arr[0]) && every(arr.slice(1), p)
```

because if the first call to `p` returns `false` we don't even bother recursing because `&&` short circuits when it can. The way you wrote it it is definitely going to do the recursion all the way to the base case before unwinding.

2023-04-20 01:10 UTC, gigamonkey commented on assignments/recursion-2/code.js
> +    return some(arr.slice(1), p) || p(arr[0])
Similarly:

```suggestion
    return p(arr[0]) || some(arr.slice(1), p)
```

will short circuit as soon as `p(arr[0])` returns `true`.

2023-04-20 20:52 UTC, ionisea commented on assignments/recursion-2/code.js
> +    return some(arr.slice(1), p) || p(arr[0])
implemented

2023-04-20 20:52 UTC, ionisea commented on assignments/recursion-2/code.js
> +    return every(arr.slice(1), p) && p(arr[0])
implemented

2023-04-20 21:10 UTC, merged